import { Resend } from 'resend';
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: 'RESEND_API_KEY is missing from environment variables' }, { status: 500 });
    }
    const resend = new Resend(process.env.RESEND_API_KEY);
    const { emails, meetingTitle, summary, transcript } = await request.json();

    if (!emails || emails.length === 0 || !summary) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const { overview, checklist } = summary;

    // Create a beautiful HTML email template
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { border-bottom: 2px solid #f0f0f0; padding-bottom: 20px; margin-bottom: 30px; }
            .logo { font-weight: 800; font-size: 24px; color: #000; letter-spacing: -0.05em; }
            .section { margin-bottom: 30px; }
            .section-title { font-weight: 700; font-size: 14px; text-transform: uppercase; letter-spacing: 0.1em; color: #666; margin-bottom: 15px; }
            .card { background: #f9f9fb; border-radius: 12px; padding: 20px; border: 1px solid #eee; }
            .decision-item { margin-bottom: 10px; display: flex; align-items: flex-start; }
            .decision-item:before { content: "✅"; margin-right: 10px; }
            .action-item { margin-bottom: 10px; display: flex; align-items: flex-start; }
            .action-item:before { content: "👉"; margin-right: 10px; }
            .transcript-box { background: #fff; border: 1px solid #eee; border-radius: 8px; padding: 15px; font-size: 13px; color: #444; max-height: 300px; overflow-y: auto; white-space: pre-wrap; }
            .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #f0f0f0; padding-top: 20px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">MEETING BRIEF</div>
            <div style="font-size: 14px; color: #666;">${new Date().toLocaleDateString('ro-RO', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
          </div>

          <div class="section">
            <div class="section-title">Overview</div>
            <div class="card">
              ${overview}
            </div>
          </div>

          ${checklist && checklist.length > 0 ? `
          <div class="section">
            <div class="section-title">Task Checklist</div>
            <div>
              ${checklist.map((task: string) => `<div class="action-item">${task}</div>`).join('')}
            </div>
          </div>
          ` : ''}

          <div class="section">
            <div class="section-title">Full Transcript</div>
            <div class="transcript-box">${transcript}</div>
          </div>

          <div class="footer">
            Generated by your AI Meeting Assistant.<br/>
            &copy; ${new Date().getFullYear()} Meeting App
          </div>
        </body>
      </html>
    `;

    const { data, error } = await resend.emails.send({
      from: 'Meeting Assistant <meetings@adspectraai.com>',
      to: emails,
      subject: meetingTitle || 'Rezumatul Ședinței & Acțiuni',
      html: html,
    });

    if (error) {
      console.error('Resend API Error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(data);
  } catch (error: any) {
    console.error('Email sending exception:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
